alias nali='vim ~/.bashrc'
alias sali='source ~/.bashrc'
alias m='most '
alias l='less '
alias g='grep -eir '
alias vim='/usr/local/Cellar/macvim/7.4-76/MacVim.app/Contents/MacOS/Vim -o'
alias vi=vim
alias gvim=mvim
alias vimdiff=mvimdiff
alias gvimdiff=mvimdiff
alias md=mkdir
if [ -f ~/.git-completion.bash ]; then
    source ~/.git-completion.bash
fi


export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home
export PATH=/tomcat/bin:$PATH

#THIS MUST BE AT THE END OF THE FILE FOR GVM TO WORK!!!
[[ -s "/Users/dans/.gvm/bin/gvm-init.sh" ]] && source "/Users/dans/.gvm/bin/gvm-init.sh"
